### ISSUE TITLE
Gerador de Getters e Setter não encontrado

### ISSUE THREAD

**Issue by raphapaulino** [codeedu/guia-rapido-java-vscode#1]
Pessoal, estou seguindo o curso de Microsserviço: Catálogo de vídeos com Java ( Back-end ) e me deparei com uma situação no VS Code (Ubuntu 20.04 LTS) após as instalações das extensões recomendadas nesse Guia Rápido, as opções de geração de código (logo abaixo da opção Debug Java) pelo menu flutuante não estava aparecendo.

Então precisei instalar outra extensão que não consta na lista: 

[Java Code Generators](https://marketplace.visualstudio.com/items?itemName=sohibe.java-generate-setters-getters)

Antes:

![Screenshot from 2021-10-13 20-07-43](https://user-images.githubusercontent.com/1793723/137224752-06091cfc-9174-43fe-a814-1b29184b1b31.png)

Depois:
![Screenshot from 2021-10-13 20-10-30](https://user-images.githubusercontent.com/1793723/137224927-858924be-952e-42eb-a412-f255f8c2743a.png)

**Comment by leonanluppi** [comment]
Olá @raphapaulino , tudo bem?

Adicionei esse plugin no guia, na etapa de plugins. Antigamente esse cara vinha junto com a Extension Pack mas pelo visto ele foi separado do mesmo.

De qualquer forma, obrigado pela contribuição.
